export const COUNTIRES_FETCH_COMPLETE = "COUNTRIES_FETCH_COMPLETE";
export const COUNTRIES_FETCH_ERROR =  "COUNTRIES_FETCH_ERROR";
export const WORLD_FETCH_COMPLETE = "WORLD_FETCH_COMPLETE";
export const WORLD_FETCH_ERROR =  "WORLD_FETCH_ERROR";
